version: '3.4'
services:
  StringReverseDemo:
    environment:
    - inputString
    image: ${DOCKER_REGISTRY-}stringreverseapp
    build:
      context: .  
      dockerfile: Dockerfile      
    volumes: 
     - /container/path
